"""Type aliases for OpenFOAM data structures."""

from ._files.typing import (
    Data,
    DataEntry,
    DataEntryLike,
    DataLike,
    Dict,
    DictLike,
    DimensionSetLike,
    Field,
    FieldLike,
    FileDict,
    FileDictLike,
    KeywordEntry,
    KeywordEntryLike,
    List,
    ListLike,
    StandaloneData,
    StandaloneDataEntry,
    StandaloneDataEntryLike,
    StandaloneDataLike,
    SubDict,
    SubDictLike,
    Tensor,
    TensorLike,
)

__all__ = [
    "Data",
    "DataEntry",
    "DataEntryLike",
    "DataLike",
    "Dict",
    "DictLike",
    "DimensionSetLike",
    "Field",
    "FieldLike",
    "FileDict",
    "FileDictLike",
    "KeywordEntry",
    "KeywordEntryLike",
    "List",
    "ListLike",
    "StandaloneData",
    "StandaloneDataEntry",
    "StandaloneDataEntryLike",
    "StandaloneDataLike",
    "SubDict",
    "SubDictLike",
    "Tensor",
    "TensorLike",
]
